### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by TrySound** [reactjs/reselect#103]
This field should point source code only with untranspilled modules. In current case for example rollup users should process all deps with babel which is too long or prebundle it separatly.
https://github.com/reactjs/reselect/blob/master/package.json#L6

You can see example here
https://github.com/reactjs/redux/blob/master/package.json#L6

**Comment by ellbee** [comment]
Hi @TrySound, thanks for the info. I'll look into it.

**Comment by ellbee** [comment]
I'm struggling to find time for this right now. Anybody want to jump in and help with a PR?

**Comment by npbee** [comment]
@TrySound, took a shot at the PR if you want to take a look.
