### ISSUE TITLE
reselect always recalculating..

### ISSUE THREAD

**Issue by fairbairn** [reactjs/reselect#126]
Given the following...

```
const sortedBorrowers = function (people, persons) {
    const sorted_roles = ['borrower', 'coborrower', null];
    console.log('SORTING!');
    return people.sort(function (a, b) {
        let a_person = persons.get(a);
        let b_person = persons.get(b);
        let index_a = sorted_roles.indexOf(a_person.get('role'));
        let a_test = index_a == -1 ? sorted_roles.length : index_a;
        let index_b = sorted_roles.indexOf(b_person.get('role'));
        let b_test = index_b == -1 ? sorted_roles.length : index_b;
        return b_test < a_test;
    });
};


const sorted_people = createSelector(
    [
        (state) => state.app.borrowers.get('people'), 
        (state) => state.app.borrowers.get('persons')
    ],
    (people, persons) => sortedBorrowers(people, persons)
);

const mapStateToProps = (state) => {
    // THESE ARE ALL IMMUTABLE OBJECTS PUT INTO PROPS
    return {
        selected_person: state.ux.get('selected_person'),
        persons: state.app.borrowers.get('persons'),
        sorted_people: sorted_people(state)
    }
};
```

and knowing that state.app.borrowers is an Immutable..

and then only thing that changes from event to event is the "selected_person",

why is the selector always re-calculating?  In this case it sorts every state change of selected_person, when people and persons have not.

What am I missing?

Shouldn't the sorted_people value be cached?

**Comment by markerikson** [comment]
Hmm.  As a first observation, note that `Array.sort()` sorts the array _in-place_ (per [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) ).  It does apparently return the array, but the way you're calling it seems like it could be a problem

**Comment by fairbairn** [comment]
Well, let's assume the sort works or may not work, which really doesn't affect the issue (btw, it's working, and returning properly)...

The issue is that it runs on every state change of selected_person, and the other two immutable values (people and persons) have not changed.

Why is it recalculating?
