### ISSUE TITLE
Typescript definition files don't support alternate array argument.

### ISSUE THREAD

**Issue by threehams** [reactjs/reselect#136]
This is valid, and used several times in the README, but is not currently supported by definition files:

```
createSelector(
  [
    (state) => state.get('stuff'),
  ],
  (stuff) => {
  
  }
)
```

**Comment by mdocter** [comment]
+1

**Comment by threehams** [comment]
This is turning out to be very difficult, and may not be possible. I'll keep looking at it. One approach involves doubling the size of the declaration files (taking the same approach as the current files).

**Comment by ellbee** [comment]
Oh, you know what, I think I was already aware of this, sorry! 😳 

https://github.com/reactjs/reselect/issues/27

If it is impossible, maybe we should add something to the docs encouraging people to use the variadic version for type checkers.

**Comment by threehams** [comment]
Got it. Today I learned about tuples.

```
    function createSelector<
        TInput, TProps, TOutput,
        T1,
        T2
    >(
        selectors: [
            Selector<TInput, TProps, T1>,
            Selector<TInput, TProps, T2>
        ],
        combiner: (
            arg1: T1,
            arg2: T2
        ) => TOutput
    ): Selector<TInput, TProps, TOutput>;
```

It's verbose, but both versions can be supported. I'll test and pull request soon.

**Comment by ellbee** [comment]
Hey, well done! Sounds good.

**Comment by threehams** [comment]
https://github.com/reactjs/reselect/pull/143

**Comment by ellbee** [comment]
Going to close this as the conversation has moved to #143
