### ISSUE TITLE
Closure and connect argument returning function

### ISSUE THREAD

**Issue by darul75** [reactjs/reselect#139]
Hi,

I have followed described pattern on README page and got to change this 

https://github.com/reactjs/reselect#containersvisibletodolistjs-3

```javascript
const VisibleTodoList = connect(
  makeMapStateToProps,
  mapDispatchToProps
)(TodoList)
```

by

```javascript
const VisibleTodoList = connect(
  makeMapStateToProps(),
  mapDispatchToProps
)(TodoList)
```

Any ideas, can it be due to our redux version ?

Thanks,

Julien

**Comment by markerikson** [comment]
I'm afraid the question isn't clear.  Can you explain your situation further?  What specific problem are you having?  What are you trying to do?

**Comment by darul75** [comment]
I have just been following home page tutorial with the following code

```javascript
const makeMapStateToProps = () => {
  const getVisibleTodos = makeGetVisibleTodos()
  const mapStateToProps = (state, props) => {
    return {
      todos: getVisibleTodos(state, props)
    }
  }
  return mapStateToProps
}
```

And then add it to connect function as a first parameter

```javascript
connect(makeMapStateToProps, ....
```

But it was not working so I replaced it by

```javascript
connect(makeMapStateToProps(), ....
```

And it worked.

"react-redux": "4.0.6",
"reselect": "2.5.1"

**Comment by ellbee** [comment]
Hmm, I'll take a look.

**Comment by ellbee** [comment]
You need react-redux 4.3 or greater.

**Comment by darul75** [comment]
Great, thx again, we had to removed our ^dependencies to match version exactly, and I had this bad effect. We will upgrade to last redux version soon.

**Comment by designbyadrian** [comment]
@darul75 Which error did you get when it "wasn't working"?

**Comment by darul75** [comment]
Hi sorry I can not remember as it was a long time ago.
