### ISSUE TITLE
Breaking changes to Typescript typings in dot release

### ISSUE THREAD

**Issue by ellbee** [reactjs/reselect#145]
Reported by b-smets:

>Not sure who is really to blame for this but please don't put breaking TS changes in dot releases.
87df18a added a mandatory TProps generic parameter between 2.5.1 and 2.5.2 which causes TS to fail to compile when using the old version. Not good at all!

**Comment by ellbee** [comment]
@b-smets I have reverted the offending commit, and published v2.5.3. on NPM. I don't use Typescript, so could you check that it solves the problem?

**Comment by b-smets** [comment]
Thanks for the quick intervention. v2.5.3 seems to fix this and everything is building fine again.

Is there a roadmap for which version will contain the extra type parameter? I would like to document this for when we upgrade to the next bigger version. ( API changes are obviously fine if they happen in major or even minor versions but doing them in the patch version is a bit scary ;-) )

**Comment by ellbee** [comment]
Yes, it wasn't intentional. There are a couple of other Typescript things outstanding, so I think we'll get them sorted out in a branch and then release them altogether as version 3. I don't see the Reselect API changing very much (if at all) at this point so the type definitions should become very stable too. What do you think? cc @threehams?

**Comment by threehams** [comment]
Ouch, sorry, thanks for the quick revert. I hadn't thought of a change in the generic as a breaking change, but that could definitely cause chaos.

Should I create issues for any outstanding work which isn't covered by pull requests? This would include being very explicit about what's being exported from the module.

**Comment by ellbee** [comment]
Hey, no worries, I should have thought about it when I made the release but mistakes happen.

Creating issues for the other outstanding work sounds good.
