### ISSUE TITLE
Typescript declaration files should use top-level import/export.

### ISSUE THREAD

**Issue by threehams** [reactjs/reselect#149]
There's a long discussion in https://github.com/Microsoft/TypeScript/issues/4665 about this. We can prevent possible global pollution problems by removing module declarations, and just using plain old ES6 import/exports within `reselect.d.ts`, as long as the first statement in the file is `import` or `export`.

Plus, it's a lot more familiar, since it directly mirrors ES6 modules.

**Comment by aikoven** [comment]
Resolved in #224.
