### ISSUE TITLE
Is this working with redux-connect (wrapper around connect)?

### ISSUE THREAD

**Issue by casertap** [reactjs/reselect#154]
I am not familiar with reselect but this looks very interesting!

Do you think reselect is compatible with redux-connect?
https://github.com/makeomatic/redux-connect

This is a wrapper around the connect method to allow server side rendering.
The most relevant part of the source code is here: https://github.com/makeomatic/redux-connect/blob/master/modules/containers/decorator.js

**Comment by ellbee** [comment]
Hi @casertap, sorry for the slow reply. I have been away and am now very busy catching up right now, so I don't have time to look into this. If you look into it yourself, please let us know what you find out. Thanks!
