### ISSUE TITLE
Lazy loading from selectors

### ISSUE THREAD

**Issue by kuon** [reactjs/reselect#166]
I need to implement lazy loading of state, for example:

```javascript

const maLazySelector = (state) => {
    if (state.myLazyObject) {
        return state.myLazyObject
    } else {
        dispatch({type: "LOAD_LAZY_OBJECT"})
        return null
    }
}
```

As `dispatch` is not passed to `mapStateToProps` I'm keeping a singleton reference to it in my lazy load code, but it feels like an absolute anti-pattern (and I cannot have multiple stores).

The above code is over simplified, my actual code queues up objects that need loading, after after a short delay of 10ms, it issues a single request to the server, then it dispatch an `UPDATE_DB` action with the new objects, that's where I need `dispatch`.

How do you handle such case?

**Comment by MattSPalmer** [comment]
My suggestion would be to keep `dispatch` well away from your selectors. Selectors are pure and should only return a derived form of your app state, free of effects. Dispatching an action is an effect.

Instead, let the laziness live in a component, maybe a higher-order component if you would like to reuse the pattern. Pass `dispatch` or a dispatch-wrapped action via mapDispatchToProps, and pass your state in via a selector as normal. Put the conditional you gave above in the render method of the component.

```JSX
function LazyLoader(Comp) {
  const wrapped = props => {
    if (props.myLazyObject === undefined) {
      props.loadLazyObject()
      // maybe return a "Loading" element here?
    }
    return <Comp {...omit(props, 'loadLazyObject')} />
  }
  return connect(selector, mapDispatchToProps)(wrapped)
}
```

On initial render, let's say `state.myLazyObject` is undefined. Thus, action is dispatched, some async side effect takes place, and the component is re-rendered with the new state passed to it as props.

With this structure, the action won't dispatch again until the component is passed an undefined `myLazyObject`, and the selector remains a pure derivation of your state.

**Comment by kuon** [comment]
It might sounds silly, but I didn't think of dispatching from `render`. Thinking about it seems natural.
