### ISSUE TITLE
Undefined state?

### ISSUE THREAD

**Issue by olalonde** [reactjs/reselect#175]
```javascript
import { createSelector, createSelectorCreator, defaultMemoize } from 'reselect'
import isEqual from 'lodash.isequal'

// create a "selector creator" that uses lodash.isEqual instead of ===
const createDeepEqualSelector = createSelectorCreator(
  defaultMemoize,
  isEqual
)

const summarySelector = s => s.summary

export const selectedFiles = createSelector(
  summarySelector,
  files => files.filter(f => f.selected && !f.picked)
)

export const selectedFileIds = createDeepEqualSelector(
  s => {
    console.log('state', s)
    return selectedFiles(s).map(f => f.id)
  },
)

selectedFileIds({ summary: [{ id: 'test' }, { id: 'test2' }] })
```

Any idea why this is outputting "undefined"?

**Comment by npbee** [comment]
I believe that's happening because `selectedFileIds` is basically a selector without any dependencies.  Selectors specifically expect at least one dependency because they are memoized based on the value that each dependency returns:  

https://github.com/reactjs/reselect#createselectorinputselectors--inputselectors-resultfunc

>createSelector(...inputSelectors | [inputSelectors], resultFunc)

>Takes one or more selectors, or an array of selectors, computes their values and passes them as arguments to resultFunc.

The fix here would be to add `selectedFiles` as a dependency of `selectedFileIds`, like this:

```js
const selectedFileIds = createDeepEqualSelector(
  selectedFiles,
  s => {
    return s.map(f => f.id)
  },
)
```

I've got a jsbin here as well to demonstrate:  http://jsbin.com/piseyu/edit?js,console.  

There's a related issue here:  https://github.com/reactjs/reselect/issues/88.  

Hope that helps!

**Comment by olalonde** [comment]
Thanks and sorry for the vague question, I was a bit tired! The thing is I have a large list of elements powered with redux/connect and wanted to avoid re-rendering when the list changed but all the element IDs were the same:

```
import React, { PropTypes } from 'react'
import { connect } from 'react-redux'

import * as selectors from '../../selectors'

import FileItem from './FileItem'

class FileList extends React.Component {
  render() {
    const { fileIds, style, stateKey } = this.props
    return (
      <div>
        <div>
          {fileIds.map(id =>
            <FileItem key={id} fileId={id} style={style} stateKey={stateKey} />
          )}
        </div>
      </div>
    )
  }
}

const mapStateToProps = (s, ownProps) => {
  const state = selectors.rootState(s, ownProps)
  const fileIds = selectors.selectedFileIds(state)
  // For performance, we only re-render based on file Ids, not content
  // of files
  return { fileIds }
}

const ConnectedFileList = connect(mapStateToProps)(FileList)

export default ConnectedFileList
```

`connect` does a shallow compare so the list would re-render every time an object in `state.summary` changed, even if the ID list remained the same.

I was trying to use reselect so that the list would be memoised based on its content (list of IDs) so that mapStateToProps would see the same array as long as the list of ID was the same.

I ended up doing:

```
const createDeepEqualSelector = createSelectorCreator(
  defaultMemoize,
  isEqual
)

const summarySelector = s => s.summary

export const selectedFiles = createSelector(
  summarySelector,
  files => files.filter(f => f.selected && !f.picked)
)

// For performance, only memoizes based on IDs
export const selectedFileIds = createDeepEqualSelector(
  s => selectedFiles(s).map(f => f.id),
  s => s,
)
```

If I understand correctly, `selectedFileIds` now always returns the same array as long as `selectedFiles(s).map(f => f.id)` returns a deep equal array.

**Comment by olalonde** [comment]
Another thing, maybe emit a warning if `createSelector` has an incorrect amount of arguments? (e.g. `arguments.length < 1`)?

**Comment by npbee** [comment]
No problem!  Yeah I think your idea should work although I might do it a bit differently.  Personally I try to avoid calling into selectors directly and instead list them as dependencies.  I find that it helps me to avoid introducing any code that might through off the memoization.  

In your example, you could potentially be doing an unnecessary `map`-ing through your selected files.  

```js
const selectedFileIds = createDeepEqualSelector(
  // The `selectedFiles` are not deeply memoized, so this `.map` will run everytime
  // However, the _results_ of this function will be deeply memoized
  s => selectedFiles(s).map(f => f.id),
  s => s
)
```

This would be equivalent to the below but without an extra `.map` if the `selectedFiles` have not changed:

```js
const selectedFileIds = createDeepEqualSelector(
  // The `selectedFiles` is now a dependent selector and its results are deeply memoized, so 
  // if the contents of the array have not changed, Reselect will not re-run the result function
  selectedFiles,
  
  // You'll only map through the selected files here if selectedFiles returns a new array
  files => files.map(f => f.id)
)
```

I've got another bin to demonstrate:  http://jsbin.com/xoqesa/edit?js,console.  

As for the warning, I could see that being useful in development maybe.

**Comment by olalonde** [comment]
Thanks.
