### ISSUE TITLE
Using reselect to transform/compute derived data for nested objects?

### ISSUE THREAD

**Issue by gskema** [reactjs/reselect#179]
Let's say we have this Redux store state:

``` js
{
  document: {
    id: 452,
    revision: 34,
    items: [
      { reference: 'REF01', quantity: 1, price: 20.00 },
      { reference: 'REF78', quantity: 3, price: 1.20 },
      { reference: 'REF65', quantity: 2, price: 3.50 },
    ],
  },
  ...
}
```

And some selectors:

``` js
const getDocument = (state) => state.document;

export const getReference = createSelector(
  getDocument,
  (doc) => {
    return doc.id + '-' + doc.revision;
    }
  }
)

export const getTotalQuantity = createSelector(
  getDocument,
  (doc) => doc.items.reduce((total, item) => total + item.quantity, 0);
)
```

I'm also using `react-redux`, so I have these components:

``` jsx
<DocumentContainer />
  <Document />
    <DocumentItem />
    <DocumentItem />
    ...
```

It'd like to pass `item.quantity * item.price` to each `<DocumentItem />`.

As far as I understand the most common use case it to compute some derived data from `state` and pass it down to a **component** as an additional prop `<Document {...document} reference={reference}`, where `reference` originates from `mapStateToProps` and `getReference`.

How would I then compute subtotals for each document item, since the `<DocumentItem />` is not connected to `state`? It's probably a bad idea to mutate `document.items`.
- Is `reselect` even used in such cases?
- Do I just make some plain selectors (that derive data, eg. `item.quantity * item.price`) with arguments (`item`) and import them to my component (eg. `<Document />` or `<DocumentItemList />` - to compute a prop for each item)?

Thanks

**Comment by HeyImAlex** [comment]
Why not just use react to do this? Use `mapStateToProps` to get the document object, and then just pass down the information as `props` to the subcomponents. Definitely for `getReference`, and even for `getTotalQuantity` it might be more performant to not use reselect at all and just to recompute it every time in render.

```javascript
class Document extends Component {
  render() {
    const doc = this.props.document
    const title = `${doc.id}-${doc.revision}`
    const totalQuantity = doc.items.reduce((total, item) => total + item.quantity, 0);
    const items = doc.items.map(item => {
      return <DocumentItem key={item.reference} {...item} />;
    })
    return (
      <div>
        <h1>{ title }</h1>
        Total quantity: {totalQuantity}
        <div>{ items }</div>
      </div>
    )
  }
}
```
