### ISSUE TITLE
Typescript : cannot find module reselect

### ISSUE THREAD

**Issue by vjau** [reactjs/reselect#181]
With typescript, when importing reselect in my code with usual es6 import syntax
```js
import {createSelector} from 'reselect';
```

The typescript compiler complains with `cannot find module reselect` (error TS2307)

Typescript version 2.0.3

tsconfig.json
```js
{
  "compilerOptions": {
    "module": "es6",
    "target": "es6",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "react"


  },
  "exclude": [
    "node_modules",
    ".meteor"
  ]
}
```

`"reselect": "^2.5.4"` in dependencies in package.json

Code working fine, but TS is complaining.

No additionnal typings added.

Thank you.

**Comment by threehams** [comment]
The tsconfig is really helpful.

Excluding node_modules also prevents Typescript from finding the typings within node_modules/reselect. You can change the module resolution setting to fix this - just add `"moduleResolution": "node"` to compilerOptions.

This applies to any npm package with bundled declaration files, such as Immutable.js.

**Comment by vjau** [comment]
That makes sense, and i can confirm that it indeed resolves the problem.
Thank you !

**Comment by islalobo** [comment]
We are having the same issue, but have not found a resolution. `"moduleResolution": "node",` was already in our tsconfig.json

**Comment by richard-ejem** [comment]
see https://stackoverflow.com/a/52720674/1660584 - `no-unused-variable` tslint rule may be causing this.
