### ISSUE TITLE
Is it ok for selector return values to be non-serializable?

### ISSUE THREAD

**Issue by igagen** [reactjs/reselect#182]
I was wondering if there are any issues (e.g. with memoization) with returning non-serializable state from a reselect selector? I understand why redux state should generally be serializable to allow for things like undo and hot reloading, but was curious if anything similar applied to reselect selector return values. I didn't see any mention of it in the docs, so I thought I'd ask before I build out a bunch of selectors in this style.

As an example, here's a selector returning a canvas context:

```
const currentIdSel = state => state.currentId

const currentContextSel = createSelector(currentIdSel, (id) => {
  const canvas = document.getElementById(id)
  return canvas.getContext("2d")
}
```

**Comment by markerikson** [comment]
Should be just fine.  I've got some a couple selectors in my own app that return a Redux-ORM Session instance just as a small optimization.  That way all the `mapState` functions that rely on my relational data will reuse the same Session instance for a given Redux state update.

**Comment by igagen** [comment]
Perfect. Thanks for the quick response!
