### ISSUE TITLE
Selectors factories recomputing in mapStateToProps?

### ISSUE THREAD

**Issue by timhwang21** [reactjs/reselect#184]
Hi,

After reading [this](https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument) in the documentations, I stumbled upon the following issue:

I am writing several selector factories that take simple arguments. However, given that most selectors are used in `mapStateToProps`, the output of the selector factory is recomputed every time a change occurs in the redux store:

``` javascript
const getFooFromState = state => state.foo;

// id can come from state, props, or whatever arbitrary computation
const getFooByIdFactory = id => createSelector(
  [getFooFromState], 
  foo => foo[id]
);
```

``` javascript
const mapStateToProps = (state, props) => ({
  // Problem: whenever mapStateToProps is called, a new selector is created, losing caching
  foo: getFooByIdFactory(props.id)(state)
});
```

A solution I've found is to pass the factory with the requisite argument as a prop to the component that needs it, but it seems like a bit of a hack, and isn't very clean.

Thanks!

Note: The reason I'm not simply accessing `props.id` as the second argument in the selector is that I've been running into issues where `props.id` is not provided in the component that I'm trying to use the selector in. I think coupling selector functionality with where it is called is a bit of an anti-pattern, and explicitly passing in what is needed is less error-prone (a POV that may be entirely off-base; any counterarguments appreciated).

Additionally, in this case it doesn't matter if `id` is in `state` or `props` -- I can just extract it from wherever and pass it as an argument.

**Comment by timhwang21** [comment]
For what it's worth, one solution I came across was to set a selector factory with parameter as a higher order prop in a component, and then remove it with `mergeProps()` for cleanliness. I'm all ears if anyone has a cleaner solution.

**Comment by toomuchdesign** [comment]
Hi @timhwang21, I've just published a micro library ([re-reselect](https://www.npmjs.com/package/re-reselect)) which wraps Reselect and covers some edge cases like yours.

You scenario might be addressed by:
```js
import { createCachedSelector } from 're-reselect';

const getFooFromState = state => state.foo;

const getFooByIdFactory = createCachedSelector(
  [getFooFromState, (state, id) => id], 
  (foo, id) => foo[id],
)(
  (state, id) => id,    // Resolver: cache selectors by id
);
```

```js
const mapStateToProps = (state, props) => ({
  // Create and call a new selector only if props.id is not found in cache
  // Otherwise call selected cached with key === props.id
  foo: getFooByIdFactory(state, props.id)
});
```
It's a new born, but I'm already using it in some project I'm currently on. Happy to hear any comment/suggestion. Cheers!

**Comment by bilby91** [comment]
@toomuchdesign Have the same problem that @timhwang21 . I think rereselect will solve our issues! Awesome idea!

**Comment by silentlight** [comment]
@toomuchdesign I am trying to figure out how is your solution using re-reselect different from below implementation:
```
const getFooById = createSelector(
  [getFooFromState, (state, id) => id], 
  (foo, id) => foo[id],
);
```
Both solutions allows you to select foo by it's id and both are not recomputed after call to mapStateToProps. Should I use re-reselect only when I want to use a component multiple times on my view?

**Comment by toomuchdesign** [comment]
Hi @silentlight, consider you need to retrieve `foo` for a set of array in the same view/page.

You would sequentially call `getFooById` with different `id's` invalidating the selector cache on each call.

`re-reselect` allows you to initialise a selector with the same interface as `getFooById` but with the ability of storing a different `reselect` selector on the fly for each requested `id`. Each stored selectors is then responsible for retrieving data for a single id.

Please read also this example:
https://github.com/toomuchdesign/re-reselect/blob/master/examples/1-join-selectors.md

Cheers
