### ISSUE TITLE
Checking the input to input selectors to prevent even them from running

### ISSUE THREAD

**Issue by ericbiewener** [reactjs/reselect#203]
Is there a reason that the input to the input selectors isn't checked to see if it's the same, thus preventing the need to even call them?

**Comment by jimbolla** [comment]
The most common use case for Reselect is in React-Redux's `mapStateToProps`, which already checks whether state+props have changed. Making Reselect also check these for changes would be doing extra work.

**Comment by ericbiewener** [comment]
But if you're using a selector across multiple `mapStateToProps` implementations (which I would think is the norm, otherwise why would you need Reselect in the first place?), then Reselect will indeed check the same input multiple times.

**Comment by jimbolla** [comment]
Here's an example:
Staring with:
```js
const getCarsByColor = (state, props) => state.cars.filter(car => car.color === props.color);
const mapStateToProps = (state, props) => ({
   cars: getCarsByColor(state, props)
});
export default connect(mapStateToProps)(CarsList);
```
and converting it to use Reselect:
```js
const getCarsByColor = createSelector(
    (state, props) => state.cars,
    (state, props) => props.color,
    (cars, color) => cars.filter(car => car.color === color)
);
const mapStateToProps = (state, props) => ({
   cars: getCarsByColor(state, props)
});
export default connect(mapStateToProps)(CarsList);
```
In this case, the value of using `createSelector` for `getCarsByColor` is that `resultFunc` may be expensive and it will produce a new array on every call, meaning the component will rerender every time state changes. The two input functions are both extremely cheap, and are only going to be called if one or both of their arguments (state or props) has changed. So doing an equality check would give no benefit and would actually use up more CPU and memory.

**Comment by ericbiewener** [comment]
In some of my selectors, I'm not passing the entire `state` into the input selectors, but just part of it. Therefore, sometimes the inputs haven't changed at all and thus the selector **could** return sooner by checking for input equality rather than checking for the equality of the input selector results. Having thought about this more, however, I realize that many times this equality of inputs check won't do you any good since you're usually (and perhaps should always?) passing in the full `state` to the selector, which will surely have changed since last time.
