### ISSUE TITLE
Question - Selector as result function

### ISSUE THREAD

**Issue by duhseekoh** [reactjs/reselect#205]
Is it appropriate to do something like:

```
const productsFeedSelector = (state) => state.feed.feedResults; // contains products
const productsSearchSelector = (state) => state.search.searchResults; // contains products

// Convert products to something better suited for consumption in a react component
const productTransformerSelector = createSelector(
  [(products) => products],
  (products) => {
    // does some transformation of the list items
  }

const transformedFeedSelector = createSelector(
  [productsFeedSelector],
  productTransformerSelector
)

const transformedSearchResultsSelector = createSelector(
  [productsSearchSelector],
  productTransformerSelector
)
```

You'll notice productTransformerSelector is my result function, which is nice, because it encapsulates everything that should happen to the list of products passed to it, and can be used as the result function of any selector that has product inputs.

Prefer stackoverflow for this type of question? If so, I can just move it over there, but figured I'd get a more quality answer here.

**Comment by markerikson** [comment]
Yep, that absolutely looks like a good idea :)

**Comment by duhseekoh** [comment]
Cool thanks, wanted to make sure I wasn't going off the rails with this. I'll close it out.
