### ISSUE TITLE
[Question] component update will cause calculate again?

### ISSUE THREAD

**Issue by mrdulin** [reactjs/reselect#208]
`there is a drawback: todos is calculated every time the component is updated. If the state tree is large, or the calculation expensive, repeating the calculation on every update may cause performance problems. `

todos is calculated every time the component is updated?

Is there any demo can explain it?

**Comment by Tix6** [comment]
```
const getVisibleTodos = (todos) => todos.filter( todo => todo.isCompleted );

const MyComponent = () =>
  <Todos todos={state.todos}>
  {getVisibleTodos(todos).map( todo => <Todo todo={todo} /> )}
  </Todos>;
```

If your component is updated, todos are filtered/calculated (by getVisibleTodos) even if there is no change about them. Reselect uses memoization to avoid this useless processing.
