### ISSUE TITLE
Enhancing createStructuredSelector to handle minimal cases

### ISSUE THREAD

**Issue by urvashi01** [reactjs/reselect#212]
Most of the places where I have used this API, I have always wanted to simply have the selectors extract a slice of the state which corresponds to the key. For eg.,
`const itemsSelector = state => state.items `
`const taxPercentSelector = state => state.taxPercent `

And I pass an object like the following - 
`{
items: itemsSelector,
taxPercent: taxPercentSelector,
}`

And I keep on creating these overly straight selectors all the time, everywhere.

The current implementation requires the invoker to pass two arguments - `selectors` and `selectorCreator`. 
Can we modify the createStructuredSelector API to accept the first argument as an array as well? That array can have keys like - items, taxPercent and we can generate the above selectors by default for each of these?

**Comment by heyimalex** [comment]
You could write a function to do this pretty easily.

```javascript
import { createSelector } from 'reselect';

function createSpecialSelector(...keys) {
  return selectorCreator(
    keys.map(key => state => state[key]),
    (...values) => {
      return values.reduce((composition, value, index) => {
        composition[keys[index]] = value
        return composition
      }, {})
    }
  )
}

const mySelector = createSpecialSelector('items', 'taxPercent');
```
