### ISSUE TITLE
How to handle null state in selector

### ISSUE THREAD

**Issue by Amurmurmur** [reactjs/reselect#214]
Hi all, here is an example of a selector I have:

```
import { createSelector } from 'reselect'
const placesSelector = state => state.places

const myselector = (places) => {
    
    if(places)
    {
       [... some computation]
        return newPlaceObjectOrMap;
    }
    return undefined;
}

export default createSelector(
    placesSelector,
    myselector
);
```

and in the container component itself, that I define it in the mapStateToProps:
```
function mapStateToProps (state) {
   return {
       mySelectorResult: myselector(state),
    }
}
```
the initial state is:
```
var InitialState = Record({
  isFetching: false,
  places: null,
  error: null
})
export default InitialState
```

Since the state is null at the very first component render, and on componentDidMount, it fetches some data from the backend, should I check for null in the selector or somehow in the component itself before calling for my selector?
Whats the best practice ? Or am I doing something wrong ?

**Comment by heyimalex** [comment]
This is totally fine, just make sure that the connected component's render is able to handle `undefined` as the value for `mySelectorResult`. I will usually use null instead of undefined but that's just personal preference.

**Comment by Amurmurmur** [comment]
@heyimalex Thank you so much for your hint. Thats exactly how I do to check for nulls in my selector.

Though if I understand it right, selectors can be used pretty much anywhere? From Components to maybe Reducers ?
Can they be used in actions? In a form of functions that take params and whats been passed to an action and output some result (maybe in a combination of data from the state) ?

**Comment by markerikson** [comment]
You _can_ use selectors in reducers, but most of the time they're used in `mapState` functions and action creators.
