### ISSUE TITLE
[Question] Simple Selectors, Performance Relative to Ramda

### ISSUE THREAD

**Issue by sdtsui** [reactjs/reselect#222]
Would anyone be able to give me more info on how `reselect` does performance optimization under the hood?

At my work, we use `ramda` a lot to fetch/compare state.  We have a lot of relatively simple selectors that either grab a prop or compare 1-3 slices of state.  What would be the difference between memoizing these hand-written selectors (with `R.memoize` or `lodash/memo`), vs using `reselect`'s `createSelector` and `createStructuredSelector`?

Thanks!

**Comment by johnhaley81** [comment]
I did some perf tests myself and found that cache hits were pretty expensive. I opened up a PR to fix this #194 which also adds a test case for performance. TL;DR before the performance increase it took ~2.5 seconds on my machine. After the changes it takes ~140 milliseconds to determine cache hits for a referentially inequal `state` and ~60 milliseconds to determine they do not need to recompute their results for a referentially equal state.

All tests were done 1E6 times.

**Comment by sdtsui** [comment]
@johnhaley81 Thanks! Replied to the issue. What's the status on #194? Looks like it's ready but unmerged for a few months? Similar question about #220 , it's newer though.

**Comment by johnhaley81** [comment]
I don't know :)

I just pinged some people so we'll see what they say.

**Comment by sdtsui** [comment]
I'll close and follow #194 (looks like it'll be merged soon) + #220 (that one is still dormant).
Feel free to comment/re-open if you have more to share on performance/cache-hits. 

Thanks so much @johnhaley81 :)
