### ISSUE TITLE
[Question] Reselect roadmap 

### ISSUE THREAD

**Issue by alex3165** [reactjs/reselect#223]
Hey @ellbee @faassen I am new collaborator to the project, @gaearon added me to this project, I am working at [Trainline](https://www.thetrainline.com/) and we massively rely on Reselect on our project so it is important for us to keep it well maintained. I would like to know if there is a roadmap for the library, I have seen that there is a branch 3.0.0 what do you guys want to release with this branch ?
One of my workmate opened a PR for the Typescript type definition file https://github.com/reactjs/reselect/pull/167

Also we are looking forward to see https://github.com/reactjs/reselect/pull/194 merged.

**Comment by ellbee** [comment]
Hi @alex3165. Welcome aboard!

#194 is now merged.
#167 I am not a typescript guy, I suggest you try pinging @threehams or @aikoven about this.

As far as other things on the roadmap, I consider Reselect to be pretty much done. I think there is a lot to be said for a simple API and I lean towards the view that things are easy to add but very difficult to remove. And if we do decide to add to the API, I think its very important that the new features have the same level of documentation that is already there.

v3 will be coming soon, is there anything you would like see in other the PRs mentioned?

**Comment by alex3165** [comment]
Thanks for your welcome and for https://github.com/reactjs/reselect/pull/194, make sense for the roadmap, I have checked the current PR and can't see anything that bring lot of value without being to disruptive with the current API.

Looking forward to see `3.0.0` released.
