### ISSUE TITLE
Type error when using created selectors as input for a new selector.

### ISSUE THREAD

**Issue by kevinwardenga** [reactjs/reselect#237]
After the upgrade to version 3.0.0 the typescript compiler complains about a non matching argument type. Using the following code:

```ts
export const selectProductStore = (state: any): State => state.productStore;
export const getEntity = createSelector(selectProductStore, store => store.entity);
export const getTitle = createSelector(getEntity, entity => entity.title);
```

Is producing the following error:
```
Argument of type 'OutputSelector<any, Product, (res: State) => Product>' is not assignable to parameter of type '[ParametricSelector<{}, {}, {}>, ...'. 
Property '0' is missing in type  'OutputSelector<any, Product, (res: State) => Product>'
```

The same code doesn't show any typing error with version 2.5.4.

**Comment by alex3165** [comment]
I noticed it as well, would be nice to add your example to https://github.com/reactjs/reselect/blob/master/typescript_test/test.ts so that we handle this use case in the typescript test and fix it. I think that is because `Selector` is not the same type as `OutputSelector` so one fix would be to only use `OutputSelector` everywhere and put `resultFunc `, `recomputations ` and `resetRecomputations ` Optional, @aikoven what do you think about it ?

**Comment by alex3165** [comment]
I tried to reproduce your issue but didn't get any error : https://github.com/alex3165/reselect/commit/388da067605a6a9ba051c5784111ea2b7b3265f7#diff-2fe2e76dc80d303b543f572094baf958R35

**Comment by kevinwardenga** [comment]
The strange thing is the code compiles fine and runs without errors, just the editor is showing the error and therefore autocompletion is broken. I tried sublime and atom both showing this error when hovering over `getEntity`.

**Comment by alex3165** [comment]
@kevinwardenga It is probably because your IDE is using an old version of Typescript

**Comment by kevinwardenga** [comment]
I've already checked that, it's using the latest typescript version (2.2.2).

**Comment by aikoven** [comment]
> After changing Selector and ParametricSelector from type to an interface the errors are gone and everything is working as expected.

As far as I remember, extending type alias was an error before. Although, latest TypeScript doesn't give me any error. Maybe your editor uses some built-in TypeScript compiler that is outdated.

Either way, I've created a PR https://github.com/reactjs/reselect/pull/240 that replaces type aliases with interfaces.

**Comment by kevinwardenga** [comment]
@aikoven you're right it's possible since version 2.2, i know managed to get sublime to recognize the local typescript version, had do reinstall the typescript package and now it's properly using version 2.2 and all error are gone. But it should be good to note in the docs that you need typescript version 2.2.x to use this package or use interfaces instead of types like in your pull request.

**Comment by aikoven** [comment]
@kevinwardenga I don't see any reason to constraint version of TS since there are no other features that require latest.

**Comment by kevinwardenga** [comment]
@aikoven yep when your pull request is getting merged there's no need to contraint the TS version.
