### ISSUE TITLE
Clarify the part of the documentation about passing a dynamic argument to a selector

### ISSUE THREAD

**Issue by balteo** [reactjs/reselect#248]
I have an doubt about the part of the reselect documentation that explains how to create a selector that takes a dynamic argument:

See link here: https://github.com/reactjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument

And see code sample below:

    import { createSelector } from 'reselect'
    import memoize from 'lodash.memoize'
    
    const expensiveSelector = createSelector(
      state => state.items,
      items => memoize(
        minValue => items.filter(item => item.value > minValue)
      )
    )
    
    const expensiveFilter = expensiveSelector(state)// Where does the state argument comes from?
    
    const slightlyExpensive = expensiveFilter(100)
    const veryExpensive = expensiveFilter(1000000)

My question relates to this line of code:

    const expensiveFilter = expensiveSelector(state)

Can someone please explain where the state argument comes from? Where is it defined?

Would it be worth clarifying this in the documentation?

**Comment by markerikson** [comment]
`state` normally refers to a Redux state tree object, typically retrieved using the `getState()` function or passed into a `mapState` function by `connect`.

**Comment by balteo** [comment]
Thanks for the clarification.
