### ISSUE TITLE
clone selectors

### ISSUE THREAD

**Issue by brigand** [reactjs/reselect#252]
In the case where you have a selector used by multiple component instances at once you need to change the selector file to account for this by wrapping the selector in a factory function.

This leads me to using factories for all of my selectors for consistency. What if, instead, reselect exposed a `.cloneSelector()` method on selectors it creates which give a copy?

This could also be used in an abstraction like this:

```js
import {
  normalFunctionSelector,
  reselectSelector,
} from './selectors';
import makeMapState from 'make-map-state'; // hypothetical module

const mapState = makeMapState({
  foo: normalFunctionSelector,
  bar: reselectSelector,
});

export default connect(mapState)(C);
```

makeMapState would check if any of the selectors have a `cloneSelector` method, and if so, use that instead of the primary selector.

**Comment by jimbol** [comment]
> where you have a selector used by multiple component instances at once you need to change the selector file to account for this by wrapping the selector in a factory function.

Could you show an example of this? I'm not sure what you mean by this.

**Comment by brigand** [comment]
@jimbol see [Sharing Selectors with Props Across Multiple Components](https://github.com/reactjs/reselect#sharing-selectors-with-props-across-multiple-components).

**Comment by toomuchdesign** [comment]
Hi @brigand, avoiding selector factories is one of the reasons why a published [re-reselect](https://github.com/toomuchdesign/re-reselect).

Re-reselect is a tiny `reselect` wrapper which implements a cached selector factory keeping the same interface of a normal selector.

This is how re-reselect would handle the ["Sharing Selectors with Props Across Multiple Components"](https://github.com/toomuchdesign/re-reselect#how-to-share-a-selector-across-multiple-components-while-passing-in-props-and-retaining-memoization) case.

Hope it helps to provide a further valuable solution to `reselect` ecosystem.
