### ISSUE TITLE
Wrong typings filename

### ISSUE THREAD

**Issue by sebelga** [reactjs/reselect#261]
I am no expert in typescript but I am trying to build another module with reselect as dependency and it does it correctly with the version `2.5.4` and not with the `3.0.1`

It seems that it comes from the name of the "typings" file.  
In 2.5.4 it is "reselect.d.ts" --> same name as the library. In 3.0.1 it is "index.d.ts".

What happens is that after I build, with the version 2.5.4 the imports in my built files are still good:

```
import { createSelector } from 'reselect';
```

But with version 3.0.1 they are transformed to:

```
import { createSelector } from 'reselect/index';
```

which obviously breaks the app.

I did rename in package.json the typings to "typings": "lib/reselect.d.ts" and update the filenname to "reselect.d.ts" and I can confirm that it works.

**Comment by aikoven** [comment]
```ts
import { createSelector } from 'reselect';
```
Above import should work fine with new typings. I guess it's your editor's autocomplete suggest a wrong import like mine does (WebStorm).

**Comment by sebelga** [comment]
That's what I said: "are still good".
So with version 2.5.4 everything is fine: `import { createSelector } from 'reselect`
But with version 3.0.1 the import is changed to: `import { createSelector } reselect/index`

**Comment by sebelga** [comment]
This is quiet a blocker, I am surprised no one has got this bug. This happen when building another library that imports "reselect". I use Rollup to build my library. When rollup converts to es5 the imports, reselect is like this:

```js
import { createSelector } from 'reselect/index';
```
Which **does not work** as the npm package or reselect does not have any index.js file (it is in the lib folder)

The workaround I am doing is to import reselect like this

```js
import "reselect/lib"
```

which then converts to this after Rollup bundles my lib to es5

```js
import { createSelector } from 'reselect/lib/index';
```

The fix I see is either

- renaming the typing to "reselect.d.ts" like I mentioned above (like it was in version 2.5.4)
- have an index.js at the root of the distributed package

thanks! :+1:

**Comment by aikoven** [comment]
>  I am surprised no one has got this bug

There's probably something wrong with your tooling. What does change the import from `reselect` to `reselect/index`?

As you can see in [Redux repo](https://github.com/reactjs/redux), the typings file is named `index.d.ts` and placed in the root, and there's no `index.js` there and everything works fine.

Also, in Reselect, there's even no `index.d.ts` file in the root (it resides in `lib/`), so `reselect/index` is twice strange.

I have no objections to renaming typings file, but I doubt that that is the root of the problem.

**Comment by sebelga** [comment]
It seems that rollup transforms imports to point to an actual file when packaging for "es5" format. So when it sees an npm import, it automatically adds the trailing "/index" as usually there is an index.js file inside an npm. Even if this index only purpose is to export * from /lib/index

**Comment by aikoven** [comment]
This still doesn't make sense. [There's](https://github.com/reactjs/reselect/blob/master/package.json#L7) a special `typings` field in `package.json` that tells TS where to look for typings. It works with bare TS compiler, and if it doesn't work with TS plugin for Rollup, you should rather file an issue there.

**Comment by sebelga** [comment]
I just look at how all the npm packages are packaged (for Angular) and I see this same pattern everywhere. Either you have an index.d.ts at the root of the folder, either you give it the same name as the library "reselect.d.ts".

I you mind changing it, I can pass over it by requiring directly reselect like this `import { createSelector} from "reselect/lib"` and it works. It's just not as nice ;)
