### ISSUE TITLE
[Question] Is reselect memozie-check still necessary, even if it works with connect() of react-redux?

### ISSUE THREAD

**Issue by mpyw** [reactjs/reselect#276]
There are some examples those work around combining reselect and [react-redux](https://github.com/reactjs/react-redux). They insist on the advantages of using reselect, especially about decreasing calcuation costs by reselect memoization.

[Reduxのreselectとは - Qiita](http://qiita.com/zaki-yama/items/5258e6f1ae37f63034b9) (Japanese)

----

> この時の問題として、**`getVisibleTodos()` は関係する `state.todos` もしくは `state.visibilityFilter` に更新があったかどうかに関わらず `state`** が更新されるたびに実行されるので、フィルタリング処理の計算コストが高かった場合パフォーマンスに影響が出てしまう。

> There is a problem at this time; **`getVisibleTodos()` is executed every time `state` is updated regardless of whether the relevant `state.todos` or `state.visibilityFilter` has been updated or not**.  If the calculation cost of the filtering process is high, the performance will be degraded.

----

> 呼ばれるたびに input selectors の戻り値（つまり `state` のうち関係する部分）に更新があったかどうかを `===` で比較し、更新がなかった場合は `resultFunc` は再実行せず、キャッシュしておいた直前の結果を利用する。
そのため、コンポーネント側からロジックが分離できただけでなく、`state` のツリーのうち、関係のある部分が更新されない限りは `getVisibleTodos()` による再計算は発生しない。

> Whenever called, it determines using `===` whether the return value of input selectors (that is, the related part of the `state`) is updated. If there is no update, re-execution of `resultFunc` will never occur and take cached results.
Therefore, the advantage is not only that the logic can be separated from the component side; recalculation by `getVisibleTodos()` will not occur unless the relevant part of the `state` tree is updated.

----

However, after taking a look at the [react-redux](https://github.com/reactjs/react-redux) sources:

- https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/src/connect/selectorFactory.js#L95-L98

- https://github.com/reactjs/react-redux/blob/f892ec00d7e92ff7afb21498276472f0e3b000c5/src/connect/connect.js#L52

I began wondering whether the memoize-check run by reselect is still necessary. Is it actually true?

**Comment by mpyw** [comment]
After reviewing the necessity of reselect, I thought:

- react-redux **only performs a `shallowEquals` comparison at the root level**; it does not do in a deeper hierarchy.

- react-redux never performs the process of automating nested `shallowEquals` calls. This is because it is a huge waste to repeatedly call nested `shallowEquals` with units smaller than the unit passed to `mapStateToProps`.

- So, developers should create arbitrary selectors for each case; we can call `shallowEquals` only once with exactly the same unit passed to `mapStateToProps`.

Right?

**Comment by markerikson** [comment]
Memoization is _absolutely_ useful in conjunction with React-Redux and `connect`.  If you use memoized selectors in your `mapState`, you increase the chances of the returned values being the same, and therefore skipping the re-rendering.

**Comment by mpyw** [comment]
@markerikson Thanks for the reply, but I would like to know more details. Is the description of my second comment  correct?

**Comment by mpyw** [comment]
I got it. My idea was wrong.

- react-redux can reduce **rerendering** costs.
- reselect can reduce **recomputation** costs.

So reselect is useful only if selector function is complex.

**Comment by markerikson** [comment]
Per my comment, Reselect is also useful for helping reduce re-rendering costs, by ensuring that new object references are only returned in a `mapState` function if the inputs have changed.  The inputs and computations don't _have_ to be complex for Reselect to be useful.

**Comment by mpyw** [comment]
Really? Please tell me how it works... I'm very interested in it.

**Comment by mpyw** [comment]
> by ensuring that **new object references**

It's very important thing

**Comment by markerikson** [comment]
I'd suggest you read these articles and resources:

- [Redux FAQ: performance and re-rendering](http://redux.js.org/docs/faq/ReactRedux.html#react-rendering-too-often)
- [Practical Redux, Part 6: Connected Lists, Forms, and Performance](http://blog.isquaredsoftware.com/2017/01/practical-redux-part-6-connected-lists-forms-and-performance/)
- [React/Redux Links: Redux Performance](https://github.com/markerikson/react-redux-links/blob/master/react-performance.md#redux-performance)

**Comment by clearyandzap** [comment]
it's 2020 and we have hooks. 

useSelect form 'reac-redux' and useMemo from 'react',  with this in mind, it seems that reselect is not necessary anymore?

**Comment by markerikson** [comment]
@clearyandzap Reselect is still absolutely useful, for exactly the same reasons.  `useSelector` re-renders your component when the value of the selector result changes.  If that selector needs to do some kind of transformation, you want to A) avoid doing that unnecessarily, and B) return the same reference as last time if the inputs didn't change.  That's what Reselect is for.  `useMemo` can't help with that.

**Comment by clearyandzap** [comment]
@markdalgleish Thank you for your prompt response! =)

**Comment by markerikson** [comment]
Mark Dalgleish is definitely not the person who just answered your question :)

**Comment by clearyandzap** [comment]
Oops... Sorry @markerikson
