### ISSUE TITLE
When adding reselect with Yarn,I  get “incorrect peer dependency”s

### ISSUE THREAD

**Issue by Y-Taras** [reactjs/reselect#281]
I've added  **`reselect`** to my app and got three warnings  
![screenshot from 2017-09-09 16 05 36](https://user-images.githubusercontent.com/8538134/30240412-c5689b58-9578-11e7-9538-0e6e45a349b5.png)
Should I ignore them?
`OS: Ubuntu 14.04 LTS`

**Comment by markerikson** [comment]
None of those warnings actually have anything to do with Reselect.  They have to do with other packages you already have installed: `ajv-keywords`, `babel-loader`, and `babel-jest`.

You should review those other libraries to see what versions they need.
