### ISSUE TITLE
Include distribution build for a browser

### ISSUE THREAD

**Issue by gajus** [reactjs/reselect#29]
If not for anything else, it is useful when setting up test examples in jsbin.com.

In case anyone comes across this while looking for browser dist and it is not yet added, you can use this gist:

* https://gist.github.com/gajus/1651f58bbcab629f9401/
* https://rawgit.com/gajus/1651f58bbcab629f9401/raw/0dbea2214b1a8ce9fb9a99f814d9aeffd04c35e1/reselect.js

or jsbin template:

* http://jsbin.com/womesekifi/1/edit?html,js,output

**Comment by ellbee** [comment]
Closed due to inactivity. The links in this issue are out of date now but a PR to add support for this to the project would be welcome.
