### ISSUE TITLE
[question] Is it an antipattern to use reselect for general purpose caching?

### ISSUE THREAD

**Issue by timhwang21** [reactjs/reselect#303]
Slightly related to the question in the FAQ: [Can I use Reselect without Redux?](https://github.com/reactjs/reselect#q-can-i-use-reselect-without-redux)

One advantage reselect has over other common memoization libraries is that most don't support caching multiple arguments out of the box. For example to enable multipe args for Lodash `memoize`, you have to pass your own resolver function, which resolves your arguments into a single key anyways.

I've been exploring using reselect as a general purpose selector, attached to React components as a class property. Example:

```jsx
class Foo extends React.Component {
  getFooSelector = createSelector(
    [args => args.foo, args => args.bar, args => args.baz],
    (foo, bar, baz) => { /* something expensive */ }
  );

  someFunction() {
    const foo = getFooSelector({ foo: something, bar: something, baz: something });
  }
}
```

I was wondering, are there any gotchas or hidden costs of doing this? So far, it's been working very well for my use case. Thank you!

**Comment by markerikson** [comment]
That's absolutely fine.  Reselect was definitely written with the intent of being used with Redux, but it is indeed a general-purpose lib that has no actual ties to Redux.  You should feel free to use it anywhere in your app.

**Comment by timhwang21** [comment]
Thank you!
