### ISSUE TITLE
Use reselect in Redux Actions or Reducers

### ISSUE THREAD

**Issue by albert-olive** [reactjs/reselect#305]
Hi, 

If I understood it right, we can use reselect in actions or reducers as @markerikson says in this post:

https://github.com/reactjs/reselect/issues/187#issuecomment-257947556

Someone has tried and could share the code? 

Thanks

**Comment by albert-olive** [comment]
Ok, don't know if it's the best way to do that. What do you think?

    import { getIsAuthenticated } from './selectors/auth';

    export function actionMethod() {
      return (dispatch, state) => {
        const isLoggedSelector = getIsAuthenticated()(state);

       ....

      }
    }

**Comment by markerikson** [comment]
@albert-olive : that's _almost_ correct.  You'd just import the selector from whatever file it's defined in, and use it.  However, the double-call there looks suspicious.  How are you defining `getIsAuthenticated` ?

**Comment by albertolive** [comment]
Yes, sure :)

    const selectAuthState = () => ({ auth }, props) => {
      return { auth, props };
    };

    const getIsAuthenticated = () => createSelector(
      selectAuthState(),
      token => !validate.isEmpty(token)
    );

I don't really remember why I did that. Maybe for caching or memoization. It's not the correct way to do that?

**Comment by markerikson** [comment]
It _can_ be useful, in certain situations, but not the way you're using it here.

For `selectAuthState`, there's _no_ reason to implement it as a factory/closure.

For `getIsAuthenticated`, the only reason to do it that way is if you need to create a unique selector instance for each component that wants to use this selector.  But, it also isn't taking any parameters, so it's not like you'd really need that in this situation anyway.

**Comment by albertolive** [comment]
Mmm ok, so, doing it that way, it will have a performance issue? 

Have in mind that now I have all my app that way.

And yes, now I remember that I did it to create a unique selector instance for each component. But maybe I misunderstood how to do it properly and if I really needed.

So no need to do it like this?

**Comment by markerikson** [comment]
I really wouldn't worry about perf for something like this, and no, you don't need to do it as factory functions that way.

**Comment by albert-olive** [comment]
Ok thanks mark!
