### ISSUE TITLE
IDE cannot resolve import from reselect

### ISSUE THREAD

**Issue by ClementWalter** [reactjs/reselect#308]
I am using Webstorm 2017.3 and I cannot fix an issue with import form `reselect`:
`Cannot resolve symbol 'createStructuredSelector'` when doing:
```
import { createStructuredSelector } from 'reselect';
```
I found similar issues on the the web concerning other packages (`react-native` for instance) so I guess it is a package related issue.

Everything works perfectly but this warning in the IDE is a bit annoying.
![image](https://user-images.githubusercontent.com/18620296/33906293-71830974-df79-11e7-93d0-f676e37ec656.png)

**Comment by 209** [comment]
You can use 'reselect/es'.

**Comment by jcicero518** [comment]
Ahh thanks 209. It can't find the `createStructuredSelector` function because there's no index.js file in the directory, hence "reselect/es"
