### ISSUE TITLE
Recalculate selector only if one of the input-selectors changed

### ISSUE THREAD

**Issue by shahafa** [reactjs/reselect#312]
Is it possible to recalculate selector only if one of the input-selectors changed?

For example, If subtotalSelector changed recalculate taxSelector and if taxPercentSelector changed return the previous calculated value?
```
const taxSelector = createSelector(
  subtotalSelector,
  taxPercentSelector,
  (subtotal, taxPercent) => subtotal * (taxPercent / 100)
)
```

**Comment by markerikson** [comment]
I may be misunderstanding what you're asking, but that sounds exactly like how Reselect works right now.  Reselect runs all of the "input selectors", compares their results to the last time, and if any of them have changed, re-runs the "output selector".

**Comment by shahafa** [comment]
Sorry for not being clear
I want to configure the selector somehow to re-run the "output selector" only if some of the "input selectors" changed

Let's say for example I have array and some logic that adds elements only to the end of the array.
I have selector to get element from the array
```
const getElement = createSelector(
  array,
  index,
  (array, index) => array[index]
)
```
There is no reason to recalculate the selector if array changed and index wasn't changed even since the element in the index will be the same
I wonder if there is a way to tell the selector - re-calculate only if index changed

**Comment by markerikson** [comment]
Two thoughts here.

First, the normal situation is that if `array` has changed to a new reference, you _would_ want to recalculate the output.  That's part of the basis of immutable data updates.  When updating data immutably, all changes are done by creating new object/array references and modifying the new copies, so a new reference means that something has changed.

For the behavior you want, you would either need to create another selector that handles the first set of inputs and use that as an input to the later selector, or use Reselect's `createSelectorCreator` function to customize the equality checking behavior.

**Comment by shahafa** [comment]
Thanks
