### ISSUE TITLE
Reselector give wrong result when delete a json object from state

### ISSUE THREAD

**Issue by jordiviva** [reactjs/reselect#318]
I have an reselect structure like this:
```
export const getThreadsState = (state): ThreadsState => {
  return state.threads;
}

export const getThreadsEntities = createSelector(
  getThreadsState,
  ( state: ThreadsState ) => {
    console.log(`Get thread entities= ${JSON.stringify(state.entities)}`)
    return state.entities;
  } );

export const getAllThreads = createSelector(
  getThreadsEntities,
  ( entities: ThreadsEntities ) => Object.keys(entities)
                        .map((threadId) => {
                          return entities[threadId];
                        }));
```

It's working allwayis, except when I delete a thread from the state doing it:
```
case ThreadActions.DELETE_THREAD: {
      const thread: Thread = (<ThreadActions.DeleteThreadAction>action).thread;

      const indexToRemove = state.ids.indexOf(thread.id);
      const newState: ThreadsState = Object.assign(
        {}, state);
      const ids = [
        ...newState.ids.slice(0, indexToRemove),
        ...newState.ids.slice(indexToRemove + 1)
      ];
      delete newState.entities[thread.id];
      return {
        ids: ids,
        currentThreadId: null,
        entities: newState.entities
      };
    }
```
## **The problem is**, when I delete one thread, getAllThreads() don't return the new state with the thread deleted even if the state had change correctly but when I add a new thread, the method returns the correct state with the thread deleted.

If i do the same code without using reselect, it works totally fine, but no Idea why it don't works with reselect.
It works:
```
export const getAllThreads = (state) => {
  return Object.keys(state.threads.entities).map((threadId) => {
    return state.threads.entities[threadId];
  });
}
```
The full file is same as https://github.com/codeyu/ng-book-code/blob/master/redux/redux-chat/src/app/thread/threads.reducer.ts but adding the feature described to delete a thread.

**Comment by erikmajlath** [comment]
Hey!

There are few small issues which together create the problem you mentioned. Simple explanation is that this code:
```
const newState: ThreadsState = Object.assign({}, state);
```
keeps the old reference to the entities (as they are sub object) and deleting from those entities do not change the reference thus reselect thinks it's the same object and it does not recompute. To solve your problem you should create new reference to entities like:
```
const newEntities = Object.assign({}, state.entities)
```
then delete form them and save it in the state.

## Object.assign

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign

> For deep cloning, we need to use other alternatives because Object.assign() copies property values. If the source value is a reference to an object, it only copies that reference value.

Look at this example
```
const entities = { ... }
const state = { entities: entities }
const z = Object.assign({}, state)

console.log(z.entities === entities) //true
```

**Comment by jordiviva** [comment]
Hi Erik,

Thanks for your response, had no idea Objct.assign just copie the reference of sub objects, I'm just starting with redux so your response helps me a lot, now everything works perfect adding
```
const newEntities = Object.assign({}, state.entities)
delete newEntities[thread.id];
```
