### ISSUE TITLE
Retaining memoization when passing props to *different* component instances.

### ISSUE THREAD

**Issue by Palisand** [reactjs/reselect#319]
The docs state that in order to share a selector across multiple component instances while passing in props and retaining memoization, each instance of the component needs its own private copy of the selector. Does this apply to instances of different components using the same selector?

selectors.js
```javascript
import {createSelector} from 'reselect';
getData = (state, props) => state.data[props.id];
// additional question: is reselect worth using for such a simple selector?
export const getDataForId = createSelector(getData, data => data);
```

foo.js
```javascript
import {getDataForId} from './selectors';
const mapStateToProps = (state, props) => ({
  dataForId: getDataForId(state, props),
});
class Foo extends Component {...}
export default connect(mapStateToProps)(Foo);
```

bar.js
```javascript
import {getDataForId} from './selectors';
const mapStateToProps = (state, props) => ({
  dataForId: getDataForId(state, props), // uses same selector as Foo
});
class Bar extends Component {...}
export default connect(mapStateToProps)(Bar);
```

index.js
```javascript
...
<Foo />
<Bar />
...
```

**Comment by markerikson** [comment]
Yes, it does - see my post [Idiomatic Redux: Using Reselect Selectors for Encapsulation and Performance](http://blog.isquaredsoftware.com/2017/12/idiomatic-redux-using-reselect-selectors/) for examples.

**Comment by crobinson42** [comment]
I wish I found that article 💯  sooner! ⬆️
