### ISSUE TITLE
Question: Mixing selectors with mapStateToProps?

### ISSUE THREAD

**Issue by tristangodfrey** [reactjs/reselect#84]
Should/can I mix selectors with standard mappings?

So something like this:

```
   const mapStateToProps = (state) => {
      return {
         loading: state.loading,
         currentRank: currentRankSelector(state),
      }
   }
```

As far as I understand selectors are purely for computing derived data, so it doesn't make sense to use selectors for raw state right?

**Comment by ellbee** [comment]
Right. Your code sample looks good to me.
