### ISSUE TITLE
createSelector w/o dependencies

### ISSUE THREAD

**Issue by m0ru** [reactjs/reselect#88]
It's really minor - we've got the following code in our project:

```javascript
export const selectAllByConnections = createSelector(
    state => state, //reselect's createSelector always needs a dependency
    state => state
        .get('connections')
        .map(connection => allByConnection(connection)(state))
);
```
I can't move the `state.get('connections')` to a different selector as i require the full state for the core selection task.

**Comment by ellbee** [comment]
There is no need for a selector in this case, just use the bare function. `createSelector` creates a selector that memoizes on its arguments, so using `createSelector` without dependencies is essentially a no-op.

**Comment by OliverJAsh** [comment]
> just use the bare function

What if we want memoization?
