### ISSUE TITLE
Documentation - typo in code example

### ISSUE THREAD

**Issue by approots** [reactjs/reselect#93]
In the first memoization example `selectors/index.js`, should `switch(filter)` instead be `switch(visibilityFilter)`?	

    import { createSelector } from 'reselect'

	const getVisibilityFilter = (state) => state.visibilityFilter
	const getTodos = (state) => state.todos

	export const getVisibleTodos = createSelector(
	  [ getVisibilityFilter, getTodos ],
	  (visibilityFilter, todos) => {
		switch (filter) {
		  case 'SHOW_ALL':
			return todos
		  case 'SHOW_COMPLETED':
			return todos.filter(t => t.completed)
		  case 'SHOW_ACTIVE':
			return todos.filter(t => !t.completed)
		}
	  }

**Comment by ellbee** [comment]
Yep, good catch. Thank you!
